import { RawRecipe, NormalizedRecipe, ValidationStatus, DuplicateStatus, DuplicateCandidate } from '../types';

export type SourceType = 'mock' | 'json' | 'csv' | 'api' | 'external';

export type ContentPermissionStatus = 'authorized' | 'public_domain' | 'pending_review' | 'unknown';

/**
 * Metadata associated with an external recipe data source.
 * Note: Missing info must remain null/unknown. Never fabricate licenses.
 */
export interface SourceMetadata {
  sourceName: string;
  sourceType: SourceType;
  sourceUrl?: string | null;
  retrievedAt: string;
  attribution?: string | null;
  license?: string | null;
  contentPermissionStatus: ContentPermissionStatus;
}

/**
 * Standard Recipe Source Adapter interface.
 * Any data source (Mock, JSON, CSV, API, External) implements this contract.
 */
export interface RecipeSourceAdapter {
  readonly name: string;
  readonly metadata: SourceMetadata;
  fetchRawRecipes(): Promise<RawRecipe[]> | RawRecipe[];
}

export type ImportDecision = 'importable' | 'needs_review' | 'rejected';

/**
 * Represents a processed recipe candidate in the import staging pipeline.
 */
export interface ImportCandidate {
  source: string;
  sourceId: string;
  rawRecipe: RawRecipe;
  normalizedRecipe: NormalizedRecipe;
  validationStatus: ValidationStatus;
  duplicateStatus: DuplicateStatus;
  errors: string[];
  warnings: string[];
  duplicateMatches: DuplicateCandidate[];
  decision: ImportDecision;
  decisionReason: string;
}

/**
 * Summary report generated by the Import Coordinator.
 */
export interface ImportReport {
  source: string;
  sourceType: SourceType;
  fetched: number;
  valid: number;
  warnings: number;
  invalid: number;
  duplicateCandidates: number;
  importable: number;
  rejected: number;
  needsReview: number;
  productionDatabaseModified: false;
  candidates: ImportCandidate[];
  startedAt: string;
  completedAt: string;
}
